
development:
  adapter: postgresql
  encoding: unicode
  database: decanter_demo_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: decanter_demo_test
  pool: 5
  host: localhost
